# -*- coding: utf-8 -*-
# AUTO-GENERATED by cos_auto.py；請勿手動修改。
# 作用：讓 `from heta import HETA as heta` 在 cos_auto.py 啟動的子程序中
#       改用 cos_heta 套件的實作（分母由 min 改為幾何平均的 cos-HETA）。
import sys as _sys
from cos_heta import HETA  # 必備：實驗腳本使用的主模組
try:
    from cos_heta import HETA2  # 選用：若 cos_heta 有 HETA2 子模組則一併轉接
except Exception:
    HETA2 = None
_sys.modules['heta.HETA'] = HETA
if HETA2 is not None:
    _sys.modules['heta.HETA2'] = HETA2
